spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.88.246:3306/turntable
    username: root
    password: 123456
    dbcp2:
          #最小连接数
          min-idle: 5
          #初始化连接数
          initial-size: 5
          #最大连接数
          max-total: 10
          #等待连接最长的超时时间
          max-wait-millis: 200
  http:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
      #上传文件大小限制
      max-file-size: 1MB
      max-request-size: 1MB